-- CREATE OR REPLACE FUNCTION tdgShortestPath (_linktable REGCLASS,
--                                             _verttable REGCLASS,
--                                             _fromGeom geometry,
--                                             _toGeom geometry,
--                                             _stress INT DEFAULT NULL)
-- RETURNS TABLE ( link_id INT,
--                 vert_id INT,
--                 road_id INT,
--                 int_id INT,
--                 move_cost INT) AS $$
--
--
-- --needs to create temporary vertices table with added verts to represent
-- --the from/to points. then pass the temp tables to
-- --tdgShortestPathVerts
--
-- RETURN ([1,2,3,4,5],[6,5,4,3,2])
--
-- $$ LANGUAGE plpgsql;
-- ALTER FUNCTION tdgShortestPath(REGCLASS,REGCLASS,geometry,geometry,INT) OWNER TO gis;
